
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

epoches: 100

use_wandb: True
wandb_name: deformable_detr_baseline
wandb_id: "20001"

num_classes: 4
remap_mscoco_category: False
fraction: 1

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./configs/dataset/dfui/images/
    ann_file: ./configs/dataset/dfui/annotations/instances_train2017.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - { type: RandomPhotometricDistort, p: 0.5 }
        - { type: RandomZoomOut, fill: 0 }
        - { type: RandomIoUCrop, p: 0.8 }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: RandomHorizontalFlip }
        - { type: Resize, size: [ 640, 640 ], }
        # - {type: Resize, size: 639, max_size: 640}
        # - {type: PadToSize, spatial_size: 640}
        - {type: ToImage}
        - {type: ConvertImageDtype}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True
  collate_fn: default_collate_fn
  pin_memory: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: configs/dataset/dfui/images/
    ann_file: configs/dataset/dfui/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops:
        # - {type: Resize, size: 639, max_size: 640}
        # - {type: PadToSize, spatial_size: 640}
        - { type: Resize, size: [ 640, 640 ], }
        - {type: ToImage}
        - {type: ConvertImageDtype}

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False
  collate_fn: default_collate_fn
  pin_memory: True

output_dir: ./output/rtdetr_r18vd_6x_coco

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
  deformable_encoder: False
  use_cross_attention: False
  use_fpn: False
  use_encoder_idx: [0, 1, 2]

RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100
  learnt_init_query: False

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

SetCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2 }
  losses: ['vfl', 'boxes']
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: { cost_class: 2, cost_bbox: 5, cost_giou: 2}
    use_focal_loss: True
    alpha: 0.25
    gamma: 2.0