
__include__: [
  './1.deformable_detr_baseline.yml',
]

use_wandb: True
wandb_name: deformable_detr+one_to_many
wandb_id: "20011"

HybridEncoder:
  deformable_encoder: False
  use_cross_attention: True

SetCriterion:

  matcher:
    type: HungarianMatcher
    o2m: 4
