
__include__: [
  './1.deformable_detr_baseline.yml',
]

use_wandb: True
wandb_name: deformable_detr+one_to_many
wandb_id: "20011"

HybridEncoder:
  deformable_encoder: False
  use_cross_attention: True

SetCriterion:
  weight_dict: { loss_vfl: 1, loss_bbox: 5, loss_giou: 2 }
  losses: [ 'vfl', 'boxes' ]
  alpha: 0.75
  gamma: 2.0
  o2m: 4

  matcher:
    type: HungarianMatcher
    o2m: 4
