
__include__: [
  './1.deformable_detr_baseline.yml',
]

use_wandb: True
wandb_name: deformable_detr_multi_scale_cross_attention
wandb_id: "200024"

HybridEncoder:
  use_cross_attention: True
  num_cross_attention_points: 196