
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]


use_wandb: True
wandb_name: fast_valid
wandb_id: 10001

num_classes: 4
remap_mscoco_category: False
# 保证数据比例平衡
fraction: 0.5

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./configs/dataset/dfui/images/
    ann_file: ./configs/dataset/dfui/annotations/instances_train2017.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - { type: RandomPhotometricDistort, p: 0.5 }
        - { type: RandomZoomOut, fill: 0 }
        - { type: RandomIoUCrop, p: 0.8 }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: RandomHorizontalFlip }
        - { type: Resize, size: [ 320, 320 ], }
        # - {type: Resize, size: 639, max_size: 640}
        # - {type: PadToSize, spatial_size: 640}
        - {type: ToImage}
        - {type: ConvertImageDtype}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: True
  batch_size: 8
  num_workers: 0
  drop_last: True
  collate_fn: default_collate_fn
  pin_memory: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: configs/dataset/dfui/images/
    ann_file: configs/dataset/dfui/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops:
        # - {type: Resize, size: 639, max_size: 640}
        # - {type: PadToSize, spatial_size: 640}
        - { type: Resize, size: [ 320, 320 ], }
        - {type: ToImage}
        - {type: ConvertImageDtype}

  shuffle: False
  batch_size: 4
  num_workers: 0
  drop_last: False
  collate_fn: default_collate_fn
  pin_memory: True

output_dir: ./output/rtdetr_r18vd_6x_coco

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 64
  expansion: 0.5
  deformable_encoder: True
  use_cross_attention: True
  use_local_attention: False
  use_self_attention: True
  use_fpn: False
  dropout: 0.1
  eval_spatial_size: [320, 320]
  use_encoder_idx: [0, 1, 2]

RTDETRTransformer:
  # dim 设置为64
  feat_channels: [64, 64, 64]
  hidden_dim: 64
  eval_idx: -1
  # decoder 设置1层
  num_decoder_layers: 1
#  num_denoising: 0
  learnt_init_query: False
  dropout: 0.1
  eval_spatial_size: [320, 320]


epoches: 10

optimizer:
  type: AdamW
  params:
    -
      params: 'backbone'
      lr: 0.001
    -
      params: '^(?=.*encoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.001
    -
      params: '^(?=.*decoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.

  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


lr_scheduler:
  type: MultiStepLR
  milestones: [5]
  gamma: 0.1
SetCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2}
  losses: ['vfl', 'boxes']
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: { cost_class: 2, cost_bbox: 5, cost_giou: 2}
    use_focal_loss: True
    alpha: 0.25
    gamma: 2.0